# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
np.random.uniform((3,3,3))

array([1.02335385, 2.33873444, 2.00753256])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
ar = np.diag(1+np.arange(4), k=-1)
print(ar)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
a = np.zeros((8,8), dtype = int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print('8*8 Checker pattern matrix: \n', a)

8*8 Checker pattern matrix: 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
ar = np.random.random((5,5))
print('Random Array:\n', ar)
nm = (ar - ar.min())/ (ar.max() - ar.min())
print('\n Normalized Matrix: \n', nm)

Random Array:
 [[0.78710701 0.87776635 0.90594758 0.49098375 0.17397746]
 [0.89135674 0.10961157 0.77021755 0.40552984 0.32235626]
 [0.47582518 0.68378176 0.88494365 0.20259534 0.66782723]
 [0.8972366  0.64503771 0.83729255 0.38494746 0.83655837]
 [0.39483534 0.71148032 0.92724227 0.87614053 0.813536  ]]

 Normalized Matrix: 
 [[0.82860812 0.93948867 0.97395562 0.46643574 0.07872245]
 [0.95611035 0.         0.80795154 0.36192167 0.26019655]
 [0.44789612 0.70223659 0.94826684 0.11372343 0.68272347]
 [0.96330169 0.65485082 0.88998736 0.33674847 0.88908942]
 [0.3488418  0.7361132  1.         0.93750022 0.860932  ]]


# 5.  How to find common values between two arrays?

__We can find common values between two arrays by np.equal() method or can simply equate both arrays but must have same size array, both gives same results.__ 

__We get True if values are equal and else false.__

In [5]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,7,9,6])
eq = np.equal(a,b)
print(eq)
e = (a==b)
print(e)

[ True  True  True False False  True]
[ True  True  True False False  True]


__If we have both 1D Array and we want to fihnd common values instead of True and False we can use np.intersect1d() method to find common values between two arrays.__

In [6]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,7,9,6])
print(np.intersect1d(a,b))

[1 2 3 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print('Yesterday:\t', yesterday)
today = np.datetime64('Today', 'D')
print('Today:\t\t', today)
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print('Tomorrow:\t', tomorrow)

Yesterday:	 2020-07-27
Today:		 2020-07-28
Tomorrow:	 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [8]:
arA = np.random.random((4,5))
arB = np.random.random((4,5))
equal = np.allclose(arA,arB)
print('Check Random array A and B are equal or not:',equal)

Check Random array A and B are equal or not: False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
ar = np.random.random(10)
print('Original Array:\n',ar)
t = ar.max()
print('Max number:',t)
re = np.where(ar==t)
ar[re] = 0
print('After replacing max value of array with 0:\n',ar)

Original Array:
 [0.10556138 0.70283546 0.67443528 0.38000744 0.11972276 0.22897129
 0.65723036 0.11167455 0.26514875 0.28981564]
Max number: 0.7028354620941567
After replacing max value of array with 0:
 [0.10556138 0.         0.67443528 0.38000744 0.11972276 0.22897129
 0.65723036 0.11167455 0.26514875 0.28981564]


__Another method to replace maximum value of random vector by 0. By simply np.argmax() method which return index value of maximum value in array.__

In [10]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.86463734 0.72192201 0.         0.62873931 0.89581674 0.44940208
 0.86310663 0.27704623 0.75815774 0.61767188]


# 9. How to print all the values of an array?

In [11]:
a = np.array([[1,2,3,4],[3,4,5,6],[4,7,9,10]])
print('Original Array:\n', a)
for i in range(len(a)):
    for j in a[i]:
        print(j)

Original Array:
 [[ 1  2  3  4]
 [ 3  4  5  6]
 [ 4  7  9 10]]
1
2
3
4
3
4
5
6
4
7
9
10


# 10.Subtract the mean of each row of a matrix

In [12]:
ar = np.array([[1,2,3,4],[4,5,6,7],[4,8,9,7],[5,7,9,12]])
print(ar)
m = 0
for i in ar:
    me = np.mean(i)
    v = np.mean(i) - m 
    m = v
     
print('Subtract the mean of each row of a matrix is:',v)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 4  8  9  7]
 [ 5  7  9 12]]
Subtract the mean of each row of a matrix is: 4.25


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [13]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print('After  add 1 to each element indexed by a second vector:\n',Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 9 0 6 2 3 8 0 3 1 4 8 2 4 5 8 5 7 6 8]
After  add 1 to each element indexed by a second vector:
 [3. 3. 3. 3. 3. 3. 3. 2. 5. 2.]


# 12.How to get the diagonal of a dot product?

In [14]:
ar1 = np.random.randint(0,10,(3,3))
ar2 = np.random.randint(0,10,(3,3))
print(ar1,'\n\n', ar2)
dotp = np.dot(ar1,ar2)
print('\n',dotp)
print('Diagonal of a dot product is: ', np.diag(dotp))

[[3 4 6]
 [7 8 4]
 [6 4 8]] 

 [[2 1 4]
 [2 2 1]
 [2 0 0]]

 [[26 11 16]
 [38 23 36]
 [36 14 28]]
Diagonal of a dot product is:  [26 23 28]


# 13.How to find the most frequent value in an array?

In [15]:
from statistics import mode
ar = np.random.randint(1,10,50)
print(ar)
mf = mode(ar)
print(mf)               

[6 2 5 6 1 8 9 2 2 7 5 3 1 3 7 5 9 4 8 7 4 1 1 8 4 1 6 8 1 7 7 4 2 3 5 4 9
 8 1 4 5 2 8 1 5 3 7 9 1 9]
1


# 14.How to get the n largest values of an array

In [16]:
x = np.arange(25)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 5
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[20 21 22 23 24]


# 15.How to create a record array from a regular array?

In [17]:
Z = np.array([("Let's", 8.9, 7),
              ("Upgrade", 4.4, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print('Original Regular array: \n',Z)
print('Created recorded array: \n',R)

Original Regular array: 
 [["Let's" '8.9' '7']
 ['Upgrade' '4.4' '2']]
Created recorded array: 
 [(b"Let's", 8.9, 7) (b'Upgrade', 4.4, 2)]
